<a href="https://colab.research.google.com/github/Szaboltz/data_science_ads/blob/master/CombinandoDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
lojaA = pd.DataFrame({
    "loja": ["A", "A", "A"],
    "dia": ["sex", "sab", "dom"],
    "valor": [7500, 9500, 8200]
})

lojaB = pd.DataFrame({
    "loja": ["B", "B", "B"],
    "dia": ["sex", "sab", "dom"],
    "valor": [5100, 8250, 9900]
})

lojaC = pd.DataFrame({
    "loja": ["C", "C"],
    "dia": ["sab", "dom"],
    "valor": [7500, 11800]
})

lojaABC = pd.concat([lojaA, lojaB, lojaC], ignore_index=True)
print(lojaABC)

  loja  dia  valor
0    A  sex   7500
1    A  sab   9500
2    A  dom   8200
3    B  sex   5100
4    B  sab   8250
5    B  dom   9900
6    C  sab   7500
7    C  dom  11800

In [5]:
d1 = pd.DataFrame({
    "carro": ["Hyundai", "Renault", "Fiat"],
})

d2 = pd.DataFrame ({
    "animal": ["Capivara", "Lobo", "Macaco"]
})

d3 = pd.concat([d1,d2], ignore_index=True)
print(d3)

     carro    animal
0  Hyundai       NaN
1  Renault       NaN
2     Fiat       NaN
3      NaN  Capivara
4      NaN      Lobo
5      NaN    Macaco

In [7]:
df_sql = pd.DataFrame({
    "email": ["elza.=_peixoto@astconsult.com.br", "carlos_pires@piscinasegura.com.br"]
})

df_python = pd.DataFrame({
    "email": ["elza.=_peixoto@astconsult.com.br", "roberto_moreira@gruporeis.net", "alice.nicole.barbisa@bb.com.br"]
})

# União (Relação de emails distintos)

alunos = pd.concat([df_sql, df_python], ignore_index=True)
print(alunos)

# Interseção (Quem fez ambos os cursos)
sql_e_python = df_sql.merge(df_python)
print(sql_e_python)

# Diferença (Quem fez só sql e fez só python)
sql_mas_nao_python = df_sql[df_sql.email.isin(df_python.email)==False]
print(sql_mas_nao_python)

# Diferença (Quem fez só python e fez só sql)
python_mas_nao_sql = df_python[df_python.email.isin(df_sql.email)==False]
print(sql_mas_nao_python)

                               email
0   elza.=_peixoto@astconsult.com.br
1  carlos_pires@piscinasegura.com.br
2   elza.=_peixoto@astconsult.com.br
3      roberto_moreira@gruporeis.net
4     alice.nicole.barbisa@bb.com.br
                              email
0  elza.=_peixoto@astconsult.com.br
                               email
1  carlos_pires@piscinasegura.com.br
                               email
1  carlos_pires@piscinasegura.com.br

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

               country  pop_country  area_country
0          Afghanistan     31056997        647500
1              Albania      3581655         28748
2              Algeria     32930091       2381740
3       American-Samoa        57794           199
4              Andorra        71201           468
..                 ...          ...           ...
222  Wallis and Futuna        16025           274
223          West Bank      2460492          5860
224     Western Sahara       273008        266000
225             Zambia     11502010        752614
226           Zimbabwe     12236805        390580

[227 rows x 3 columns]

In [19]:
flags = pd.read_csv("/content/drive/MyDrive/ADS/DataScience/Source/flags.csv")
countries = pd.read_csv("/content/drive/MyDrive/ADS/DataScience/Source/countries.csv")

num_linhas_flags = flags.shape[0]
num_linhas_countries = countries.shape[0]

print(f"Número de linhas em flags: {num_linhas_flags}")
print(f"Número de linhas em countries: {num_linhas_countries}")

# Junção interna: paises comuns a ambas as bases
ambas = pd.merge(flags, countries, how="inner", left_on="name", right_on="country")
print(ambas)
num_linhas_ambas = ambas.shape[0]
print(f"Número de linhas em ambas: {num_linhas_ambas}")

#Left Join: paises apenas em flags
flags_only = pd.merge(flags, countries, how="left", left_on="name", right_on="country")
flags_only = flags_only[pd.isnull(flags_only['country'])==True]
num_flags_only = flags_only.shape[0]
print(f"Número de linhas em flags_only: {num_flags_only}")
print(flags_only)

#Right Join: paises apenas em coutries
countries_only = pd.merge(flags, countries, how="right", left_on="name", right_on="country")
countries_only = countries_only[pd.isnull(countries_only['country'])==True]
num_countries_only = countries_only.shape[0]
print(f"Número de linhas em countries_only: {num_countries_only}")
print(countries_only)

Número de linhas em flags: 194
Número de linhas em countries: 227
               name  landmass  zone  area  population  language  religion  \
0       Afghanistan         5     1   648          16        10         2
1           Albania         3     1    29           3         6         6
2           Algeria         4     1  2388          20         8         2
3    American-Samoa         6     3     0           0         1         1
4           Andorra         3     1     0           0         6         0
..              ...       ...   ...   ...         ...       ...       ...
172         Vanuatu         6     2    15           0         6         1
173       Venezuela         2     4   912          15         2         0
174         Vietnam         5     1   333          60        10         6
175          Zambia         4     2   753           6        10         5
176        Zimbabwe         4     2   391           8        10         5

     bars  stripes  colours  ...  crescent  triangle  icon  animate  text  \
0       0        3        5  ...         0         0     1        0     0
1       0        0        3  ...         0         0     0        1     0
2       2        0        3  ...         1         0     0        0     0
3       0        0        5  ...         0         1     1        1     0
4       3        0        3  ...         0         0     0        0     0
..    ...      ...      ...  ...       ...       ...   ...      ...   ...
172     0        0        4  ...         0         1     0        1     0
173     0        3        7  ...         0         0     1        1     0
174     0        0        2  ...         0         0     0        0     0
175     3        0        4  ...         0         0     0        1     0
176     0        7        5  ...         0         1     1        1     0

     topleft  botright         country  pop_country  area_country
0      black     green     Afghanistan     31056997        647500
1        red       red         Albania      3581655         28748
2      green     white         Algeria     32930091       2381740
3       blue       red  American-Samoa        57794           199
4       blue       red         Andorra        71201           468
..       ...       ...             ...          ...           ...
172    black     green         Vanuatu       208869         12200
173     gold       red       Venezuela     25730435        912050
174      red       red         Vietnam     84402966        329560
175    green     brown          Zambia     11502010        752614
176    green     green        Zimbabwe     12236805        390580

[177 rows x 33 columns]
Número de linhas em ambas: 177
Número de linhas em flags_only: 17
                   name  landmass  zone   area  population  language  \
9             Argentine         2     3   2777          28         2
56   Falklands-Malvinas         2     3     12           0         1
65          Germany-FRG         3     1    249          61         4
88          Ivory-Coast         4     4    323           7         3
92            Kampuchea         5     1    181           6        10
103            Malagasy         4     2    587           9        10
109            Marianas         6     1      0           0        10
127                Niue         6     3      0           0         1
135             Parguay         2     3    407           3         2
155         South-Yemen         5     1    288           2         8
163             Surinam         2     4     63           0         6
182     US-Virgin-Isles         1     4      0           0         1
184                USSR         5     1  22402         274         5
186        Vatican-City         3     1      0           0         6
189       Western-Samoa         6     3      3           0         1
190          Yugoslavia         3     1    256          22         6
191               Zaire         4     2    905          28        10

     religion  bars  stripes  colours  ...  crescent  triangle  icon  animate  \
9           0     0        3        3  ...         0         0     0        0
56          1     0        0        6  ...         0         0     1        1
65          1     0        3        3  ...         0         0     0        0
88          5     3        0        3  ...         0         0     0        0
92          3     0        0        2  ...         0         0     1        0
103         1     1        2        3  ...         0         0     0        0
109         1     0        0        3  ...         0         0     1        0
127         1     0        0        4  ...         0         0     0        0
135         0     0        3        6  ...         0         0     1        1
155         2     0        3        4  ...         0         1     0        0
163         1     0        5        4  ...         0         0     0        0
182         1     0        0        6  ...         0         0     1        1
184         6     0        0        2  ...         0         0     1        0
186         0     2        0        4  ...         0         0     1        0
189         1     0        0        3  ...         0         0     0        0
190         6     0        3        4  ...         0         0     0        0
191         5     0        0        4  ...         0         0     1        1

     text  topleft  botright country  pop_country  area_country
9       0     blue      blue     NaN          NaN           NaN
56      1    white      blue     NaN          NaN           NaN
65      0    black      gold     NaN          NaN           NaN
88      0      red     green     NaN          NaN           NaN
92      0      red       red     NaN          NaN           NaN
103     0    white     green     NaN          NaN           NaN
109     0     blue      blue     NaN          NaN           NaN
127     0    white      gold     NaN          NaN           NaN
135     1      red      blue     NaN          NaN           NaN
155     0      red     black     NaN          NaN           NaN
163     0    green     green     NaN          NaN           NaN
182     1    white     white     NaN          NaN           NaN
184     0      red       red     NaN          NaN           NaN
186     0     gold     white     NaN          NaN           NaN
189     0     blue       red     NaN          NaN           NaN
190     0     blue       red     NaN          NaN           NaN
191     0    green     green     NaN          NaN           NaN

[17 rows x 33 columns]
Número de linhas em countries_only: 0
Empty DataFrame
Columns: [name, landmass, zone, area, population, language, religion, bars, stripes, colours, red, green, blue, gold, white, black, orange, mainhue, circles, crosses, saltires, quarters, sunstars, crescent, triangle, icon, animate, text, topleft, botright, country, pop_country, area_country]
Index: []

[0 rows x 33 columns]